apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  NODE_ENV: production
# stringData:
#   .env: |
#     NODE_ENV=production
#     PORT=8080
#     DB_NAME=much_todo_db
#     MONGODB_URI=mongodb://user:pass@mongodb:27017/muchtodo?authSource=admin
#     JWT_SECRET_KEY=your-super-secret-key-that-is-long-and-random
#     JWT_EXPIRATION_HOURS=72
#     LOG_LEVEL=DEBUG
#     LOG_FORMAT=json
#     INTEGRATION=true
